# Generated by Django 5.0.6 on 2024-06-03 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingEffectiveness',
            fields=[
                ('evaluations_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semesters', models.CharField(max_length=10)),
                ('academic_yr', models.CharField(max_length=50)),
                ('student_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sr_interpretation', models.CharField(max_length=50)),
                ('supervisor_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sp_interpretation', models.CharField(max_length=50)),
                ('average_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ar_interpretation', models.CharField(max_length=50)),
                ('eval_performance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.faculty')),
            ],
        ),
    ]
