# Generated by Django 5.0.6 on 2024-06-04 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuingDevelopment',
            fields=[
                ('prodev_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=50)),
                ('hrs_accumulated', models.CharField(max_length=50)),
                ('event_date', models.CharField(max_length=50)),
                ('prodev_performance_score', models.IntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodevelopment', to='accounts.faculty')),
            ],
        ),
    ]
