# Generated by Django 5.0.6 on 2024-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_type', models.CharField(max_length=50)),
                ('faculty_rank', models.CharField(max_length=50)),
            ],
        ),
    ]
