# Generated by Django 5.0.6 on 2024-06-04 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCounts',
            fields=[
                ('research_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('output_type', models.CharField(max_length=50)),
                ('journal_publisher', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('date_published', models.CharField(max_length=50)),
                ('year_published', models.CharField(max_length=4)),
                ('research_performance_score', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='accounts.faculty')),
            ],
        ),
    ]
